# Generated by Django 5.1.1 on 2024-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name e.g. John Doe', max_length=200)),
                ('email', models.EmailField(help_text='Your email address e.g. johndoe@email.com', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Your phone number e.g. +12 34 56789-0123', max_length=20, null=True)),
                ('subject', models.CharField(help_text='A brief description of your message', max_length=100)),
                ('message', models.TextField(help_text='The message you want to send')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
