# Generated by Django 5.1.1 on 2024-09-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(help_text="The sender's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(help_text='The message content'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(help_text="The sender's name", max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(blank=True, help_text="The sender's phone number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the message was sent'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(help_text='The subject of the message', max_length=100),
        ),
    ]
